---
- name: Creating Welcome Message
  hosts: servera199
  strategy: free
  gather_facts: False
  become: true
  tasks:
  - name: Welcome to the RHCSA 9 Study/Test Environment!
    debug:
      msg:
        - ' The repo server, Server A, and Server B have been set up successfully!'
        - '------------------------------------------------------------------------'
        - ' Server A is rebooting.  If you are unable to access it right away,'
        - ' wait a couple moments, then try again.'
        - '------------------------------------------------------------------------'
        - ' Accessing The Systems:'
        - '- Server A - 192.168.56.150'
        - '- Server B - 192.168.56.151'
        - '- Username/Password - vagrant/vagrant or root/password'
        - '- Access example - `ssh root@192.168.56.150` or `vagrant ssh system1`'
        - ' -----------------------------------------------------------------------'
        - '- Two additional interfaces and drives are on Server B.'
        - '- Happy Studying!'